name: Update AH strategy rewards proof
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # once a week on Sunday at midnight

jobs:
  rebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - run: |
          yarn install
          yarn hardhat compile

      - run: |
          yarn hardhat ahProofUpdate --network mainnet-prod
        env:
          DEPLOYER_PK: ${{ secrets.DEPLOYER_PK }}

      - run: |
          curl -X POST -H "Content-Type: application/json" "$DISCORD_WEBHOOK_URL" \
            -d '{"content": "XUSD: Alpha Homora strategy rewards proof updated"}'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
