name: Mainnet periodic rebase
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */16 * * *"

jobs:
  rebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - run: echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV

      - if: env.PROCEED == '0'
        run: |
          yarn install
          yarn hardhat compile

      - if: env.PROCEED == '0'
        run: |
          sleep $((RANDOM%60))
          yarn hardhat rebase --network mainnet-prod
        env:
          DEPLOYER_PK: ${{ secrets.DEPLOYER_PK }}

      - if: env.PROCEED == '0' && always()
        run: |
          curl -X POST -H "Content-Type: application/json" "$DISCORD_WEBHOOK_URL" \
            -d "{\"content\": \"XUSD rebase ${ACTION_STATUS}\"}"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ACTION_STATUS: ${{ github.action_status }}
