name: Mainnet periodic rebase
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  rebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV
          echo "PROCEED_ALLOCATE=$((RANDOM%10))" >> $GITHUB_ENV

      - if: env.PROCEED == '0' || env.PROCEED_ALLOCATE == '0'
        run: |
          yarn install
          yarn hardhat compile

      - if: env.PROCEED == '0'
        run: |
          sleep $((RANDOM%60))
          yarn hardhat rebase --network mainnet-prod
          curl -X POST -H "Content-Type: application/json" "$DISCORD_WEBHOOK_URL" \
            -d '{"content": "XUSD rebase completed"}'
        env:
          DEPLOYER_PK: ${{ secrets.DEPLOYER_PK }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - if: env.PROCEED_ALLOCATE == '0'
        run: |
          sleep $((RANDOM%60))
          yarn hardhat allocate --network mainnet-prod
          curl -X POST -H "Content-Type: application/json" "$DISCORD_WEBHOOK_URL" \
            -d '{"content": "XUSD allocate completed"}'
        env:
          DEPLOYER_PK: ${{ secrets.DEPLOYER_PK }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
